require('options')
require('keymaps')
require('plugins')
require('colorscheme')
require('lsp')
require('treesitter')
require('telescope_settings')
require('nvtree')
require('neotest_setup')
require('dap_go')

require('style_lualine')
require('style_webdevicons')

require('config.autocmds')
require('config.dap')
